spring:
  application:
    name: ride-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:3306/ride-service?createDatabaseIfNotExist=false&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:ad_on_wheels_user}
    password: ${MYSQL_PASSWORD:test}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

eureka:
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
