spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth-service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ad_on_wheels_user
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration-ms: 3600000 # 1 hour in milliseconds  // TODO CHANGE LATER // for how long will the TOKEN BE VALID


services:
  driver-service:
    url: "http://driver-service"
  company-service:
    url: "http://company-service"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8085