spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth-service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ad_on_wheels_user
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

jwt:
  secret: ${JWT_SECRET_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8085