server:
  port: 8085

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://mysql:3306/auth-service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

eureka:
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 5
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration-ms: 3600000 # 1 hour

google:
  client-id: "1009636850818-ju60fnmur0s7dvlr0qrp0cujl7u1l3e2.apps.googleusercontent.com"

services:
  driver-service:
    url: "http://driver-service"
  company-service:
    url: "http://company-service"