spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s

jwt:
  secret: ${JWT_SECRET_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG